name: lightify
description: Lightify application

publish_to: 'none' 

version: 1.4.6+55

environment:
  sdk: '>=3.0.0 <=3.19.6'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter  

  # Firebase
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3

  # MQTT
  mqtt_client: ^10.5.1

  # Network
  dio: ^5.4.3+1

  # UI
  flutter_bloc: ^7.3.3  
  hydrated_bloc: ^7.1.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  simple_animations: ^5.0.2
  # flutter_colorpicker: ^1.0.3
  fluttertoast: ^8.2.5
  adaptive_dialog: ^2.1.0
  flutter_platform_widgets: ^6.1.0
  flutter_slidable: ^3.1.0
  # device_preview: ^1.1.0
  automatic_animated_list: ^1.1.0
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker.git
      ref: master

  # Local DB
  shared_preferences: ^2.2.3

  # Dependencies
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  injectable: ^2.4.1
  freezed_annotation: ^2.4.1
  
  # async utils
  synchronized: ^3.1.0+1

  # connection
  connectivity_plus: ^5.0.2

  # device/package info
  device_info_plus: ^9.1.2
  package_info_plus: ^8.1.0

  # platform home widgets
  home_widget: ^0.7.0

  # file manager
  path_provider: ^2.1.3

  # list reorder
  reorderables: ^0.6.0
  
  # adaptive UI
  flutter_adaptive_ui: ^0.8.0+1

  # functional programming features
  dartz: ^0.10.1  


dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  analyzer: ^6.4.1
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# flutter pub get
# flutter pub run flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"  
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"  

# flutter pub clean
# flutter pub get
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: true
  color: "#000000" 
  image: "assets/images/app_splash_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:

    # - family: Nunito
    #   fonts:
    #     - asset: assets/fonts/Nunito/Nunito-Light.ttf
    #     - asset: assets/fonts/Nunito/Nunito-Regular.ttf
    #     - asset: assets/fonts/Nunito/Nunito-Medium.ttf          
    #     - asset: assets/fonts/Nunito/Nunito-Bold.ttf
    #     - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf

    # - family: NotoSans
    #   fonts:
    #     - asset: assets/fonts/NotoSans/NotoSans-Light.ttf
    #     - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
    #     - asset: assets/fonts/NotoSans/NotoSans-Medium.ttf          
    #     - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
    #     - asset: assets/fonts/NotoSans/NotoSans-SemiBold.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
