name: lightify
description: Lightify application

publish_to: 'none' 

version: 1.4.2+45

environment:
  sdk: '>=3.0.0 <3.13.9'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter  

  # Firebase
  firebase_core: ^2.13.0  
  firebase_crashlytics: ^3.3.1

  # MQTT
  mqtt_client: ^10.0.0

  # Network
  dio: ^5.4.2+1

  # UI
  flutter_bloc: ^7.3.3  
  hydrated_bloc: ^7.1.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  simple_animations: ^5.0.0+3
  # bottom_bar_matu: ^1.3.0
  flutter_colorpicker: ^1.0.3
  # fading_edge_scrollview: ^3.0.0
  fluttertoast: ^8.2.2
  adaptive_dialog: ^1.10.1
  flutter_platform_widgets: ^3.3.5
  flutter_slidable: ^3.1.0
  device_preview: ^1.1.0
  automatic_animated_list: ^1.1.0

  # Local DB
  shared_preferences: ^2.1.1

  # Dependencies
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  injectable: ^2.1.1
  freezed_annotation: ^2.2.0
  
  # async utils
  synchronized: ^3.1.0

  # connection
  connectivity_plus: ^4.0.1

  # device/package info
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2

  # platform home widgets
  home_widget: ^0.4.0

  # file manager
  path_provider: ^2.1.2

  # list reorder
  reorderables: ^0.6.0
  
  # adaptive UI
  flutter_adaptive_ui: ^0.8.0+1

  # functional programming features
  dartz: ^0.10.1  


dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.1.5
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  freezed: ^2.3.4
  analyzer: ^5.12.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

# flutter pub get
# flutter pub run flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"  
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"  

# flutter pub clean
# flutter pub get
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: true
  color: "#000000" 
  image: "assets/images/app_splash_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:

    # - family: Nunito
    #   fonts:
    #     - asset: assets/fonts/Nunito/Nunito-Light.ttf
    #     - asset: assets/fonts/Nunito/Nunito-Regular.ttf
    #     - asset: assets/fonts/Nunito/Nunito-Medium.ttf          
    #     - asset: assets/fonts/Nunito/Nunito-Bold.ttf
    #     - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf

    # - family: NotoSans
    #   fonts:
    #     - asset: assets/fonts/NotoSans/NotoSans-Light.ttf
    #     - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
    #     - asset: assets/fonts/NotoSans/NotoSans-Medium.ttf          
    #     - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
    #     - asset: assets/fonts/NotoSans/NotoSans-SemiBold.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
